apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-app-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "standard"
  volumeName: demo-app-pv
