apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: app-code
          mountPath: /var/www/html
  volumes:
    - name: app-code
      hostPath:
        path: /home/sal/projects/kubernetes-demo
        type: Directory
