apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: default
spec:
  selector:
    app: demo-app
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  type: ClusterIP
